development:
  sessions:
    default:
      database: cs_comments_service_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: cs_comments_service_test
      hosts:
        - localhost:27017

defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true
