development:
  sessions:
    default:
      database: cs_comments_service_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: cs_comments_service_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      hosts:
        - <%= ENV['MONGOHQ_HOST'] + ':' + ENV['MONGOHQ_PORT'] %>
      username: <%= ENV['MONGOHQ_USER'] %>
      password: <%= ENV['MONGOHQ_PASS'] %>
      database: <%= ENV['MONGOHQ_DB'] %>
      options:
        skip_version_check: true
        safe: true
        consistency: strong

edgeprod:
  sessions:
    default:
      hosts:
        - sayid.member1.mongohq.com:10001
      username: <%= ENV['MONGOHQ_USER'] %>
      password: <%= ENV['MONGOHQ_PASS'] %>
      database: app10640640
      options:
        skip_version_check: true
        safe: true
        consistency: strong

edgestage:
  sessions:
    default:
      hosts:
        - vincent.mongohq.com:10001
      username: <%= ENV['MONGOHQ_USER'] %>
      password: <%= ENV['MONGOHQ_PASS'] %>
      database: app10640673
      options:
        skip_version_check: true
        safe: true
        consistency: strong

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

loadtest:
  sessions:
    default:
      hosts:
        - sayid.member0.mongohq.com:10007
        - sayid.member1.mongohq.com:10007
      username: <%= ENV['MONGOHQ_USER'] %>
      password: <%= ENV['MONGOHQ_PASS'] %>
      database: app7276251
      options:
        skip_version_check: true
        safe: true

defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true
