development:
  sessions:
    default:
      database: cs_comments_service_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: cs_comments_service_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

loadtest:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true
