development:
  host: localhost
  database: cs_comments_service_development

test:
  host: localhost
  database: cs_comments_service_test

defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true
